pipeline_name: block_place_image
# env
env_name: block_place_image
abs_action: false
dataset_path: dev/block_place/block_place_replay.zarr
mode: train
max_episode_steps: 100
obs_keys: ['image0', 'image1', 'state', 'action']
shape_meta:
  obs:
    agent_pos:
      shape:
      - 7
      type: low_dim
    image0:
      shape:
      - 3
      - 240
      - 320
      type: rgb
    image1:
      shape:
      - 3
      - 240
      - 320
      type: rgb
action_dim: 7
obs_steps: 4
action_steps: 4
# obs_encoder
rgb_model: resnet18
resize_shape: null
crop_shape: null
random_crop: false
use_group_norm: true
use_seq: true
# train
device: cuda:3
seed: 0
gradient_steps: 10000
batch_size: 64
horizon: 10
nn: dit
diffusion: ddpm
sample_steps: 5
# optimizer
lr: 0.0001
# eval
model_path: path/to/model
eval_episodes: 5
num_envs: 1
eval_freq: 100
save_video: true
# log
exp_name: ${env_name}_abs_${abs_action}_${nn}_${diffusion}_sample_${sample_steps}_horizon_${horizon}
save_path: logs
project: CleanDiffuser
group: dp_pusht
wandb_mode: offline
log_freq: 100
save_freq: 100
work_dir: ${save_path}/${pipeline_name}/${mode}/${env_name}/${exp_name}_${now:%Y%m%d_%H%M%S}/${seed}
# hydra
hydra:
  run:
    dir: ${work_dir}
  job:
    chdir: false